#!/usr/bin/env bash
set -euo pipefail
cd "$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
cd web-server
PATH=$PATH:./node_modules/.bin

echo 'Resetting database...'
cat ./db/reset.sql | sudo -u postgres psql -a
