#!/usr/bin/env bash
set -euo pipefail
cd "$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
PATH=$PATH:./node_modules/.bin

####################################################################################################
# Upgrade system
####################################################################################################
sudo yum update -y

####################################################################################################
# Database
####################################################################################################

# Install npm
if ! hash npm; then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  source ~/.nvm/nvm.sh
  nvm install node
fi

# Is postgres db installed?
if ! hash psql; then
  sudo yum install postgresql96-server.x86_64 -y
  sudo service postgresql96 initdb
  sudo sed -i '1ilisten_addresses = '"'*'" /var/lib/pgsql96/data/postgresql.conf 
  sudo sed -i '1ihost webstack webstack 0.0.0.0/0 md5\nlocal webstack webstack md5\n' /var/lib/pgsql96/data/pg_hba.conf
  sudo chkconfig postgresql96 on
  sudo service postgresql96 start
fi

# Is postgres db running?
if ! sudo su postgres -c 'cd ~/ && echo "" | psql' 2>/dev/null ; then
  sudo service postgresql96 start
fi

####################################################################################################
# App Setup
####################################################################################################

# Install app dependencies
cd server
npm install

cd ../web
npm install
cd ..


####################################################################################################
# Build initial project
####################################################################################################

./db-reset
./build
